name: TFLint

on:
  workflow_call:
  workflow_dispatch:

jobs:
  tflint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Setup TFLint with checksum verification
        uses: terraform-linters/setup-tflint@90f302c255ef959cbfb4bd10581afecdb7ece3e6 # 4.1.1
        with:
          tflint_version: v0.58.0
          checksums: |
            1e8ccdf3e4b57ba154545b4343621bf46f25ca8f5cc97e36432469752f7ef0c0

      - name: Initialise & Install TFLint AWS Ruleset Plugin
        run: tflint --init

      - name: Run TFLint
        run: tflint
