name: Sync to another org
on:
  workflow_call:
  workflow_dispatch:
  push:
    branches: main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Generate token for your org's repo
        id: app-token
        uses: actions/create-github-app-token@v3
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.SYNC_APP_PRIVATE_KEY }}
          repositories: test
          owner: kurtismash2
          permission-contents: write
          permission-workflows: write

      - name: Sync to target repo
        env:
          TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          git clone --bare https://github.com/kurtismash/actions-test.git
          cd actions-test.git
          git push --mirror https://x-access-token:${TOKEN}@github.com/kurtismash2/test.git
